apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: frontend
    labels:
      app: frontend
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: frontend
    labels:
      app: frontend
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: frontend:${OUTPUT_IMAGE_STREAM_TAG}
    source:
      type: Binary
      binary: {}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ruby:2.3
          namespace: openshift
- description: The image stream tag to build to.
  displayName: Output image stream tag
  name: OUTPUT_IMAGE_STREAM_TAG
