---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4
