---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/omallo/openshift/volumes/disk-1
