apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: frontend
    name: frontend
  spec:
    replicas: 1
    selector:
      app: frontend
      deploymentconfig: frontend
    template:
      metadata:
        labels:
          app: frontend
          deploymentconfig: frontend
      spec:
        containers:
        - image: rubex-dev/${IMAGE_STREAM_TAG}
          name: frontend
          ports:
          - containerPort: 8080
            protocol: TCP
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - frontend
        from:
          kind: ImageStreamTag
          name: ${IMAGE_STREAM_TAG}
          namespace: rubex-dev
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: frontend
    name: frontend
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: frontend
      deploymentconfig: frontend
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: frontend
    name: frontend
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: frontend
parameters:
- description: The image stream tag from which to deploy.
  displayName: Image Stream Tag
  name: IMAGE_STREAM_TAG
