apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: frontend
    labels:
      app: frontend
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: frontend
    labels:
      app: frontend
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: frontend:latest
    source:
      type: Git
      git:
        uri: https://github.com/omallo/ruby-ex
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ruby:2.3
          namespace: openshift
