dev:
  build:
    frontend:
      templates:
      - manifest: deployment/manifests/build.yaml
        parameters:
          OUTPUT_IMAGE_STREAM_TAG: b-master
  deployment:
    frontend:
      templates:
      - manifest: deployment/manifests/app.yaml
        parameters:
          ENV: dev
          REPLICAS: 1
test:
  deployment:
    frontend:
      templates:
      - manifest: deployment/manifests/app.yaml
        parameters:
          ENV: test
          REPLICAS: 2
