dev:
  build:
    frontend:
      templates:
      - manifest: deployment/manifests/build.yaml
  deployment:
    frontend:
      delete:
      - type: pvc
        name: frontend-data
      templates:
      - manifest: deployment/manifests/app.yaml
        parameters:
          ENV: dev
          REPLICAS: 1
test:
  deployment:
    frontend:
      delete:
      - type: pvc
        name: frontend-data
      templates:
      - manifest: deployment/manifests/app.yaml
        parameters:
          ENV: test
          REPLICAS: 2
