---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: frontend
  name: frontend
---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  source:
    git:
      uri: https://github.com/omallo/ruby-ex
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ruby:2.3
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: vo6X68zZF5Vo7Gr3VE6i
    type: GitHub
  - generic:
      secret: 1mmeM9GOBvY2aS7rlF0f
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
