---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: frontend
  name: frontend
---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  source:
    type: Git
    git:
      uri: https://github.com/omallo/ruby-ex
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ruby:2.3
        namespace: openshift
  triggers:
  - type: GitHub
    github:
      secret: vo6X68zZF5Vo7Gr3VE6i
  - type: Generic
    generic:
      secret: 1mmeM9GOBvY2aS7rlF0f
  - type: ConfigChange
  - type: ImageChange
    imageChange: {}
status:
  lastVersion: 0
